apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-Deployment
  namespace: mern-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: tarunguduru2811/mern-backend:3ebcb0e43a2894319754849d5d30953a2f3b5aea
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
          name: backend-config
        - secretRef:
          name: backend-secrets
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10