apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: mern-app
type: Opaque
stringData:
  MONGO_USERNAME: "admin"
  MONGO_PASSWORD: "password"
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGODB_URI: "mongodb://root:password@mongo-service:27017/tododb?authSource=admin"
