frontend:
  replicaCount: 2
  image:
    repository: tarunguduru2811/todo-frontend
    tag: "b20a009818569797fafd24391bd5542a55eb7dab"
  service:
    type: NodePort
    port: 80
    nodePort: 32000
  
backend:
  replicaCount: 2
  image:
    repository: tarunguduru2811/todo-backend
    tag: "b20a009818569797fafd24391bd5542a55eb7dab"
  service:
    type: ClusterIP
    port: 5000

mongo:
  image:
    repository: mongo
    tag: "6"
  storage: 2Gi
  auth:
    rootUsername: root
    rootPassword: password
    appUsername: admin
    appPassword: password
    database: tododb

ingress:
  host: mern.local