apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mern-app.fullname" . }}-backend-monitor
  labels:
    release: prometheus-grafana # This must match the release name or namespace selector for your prometheus!
    {{- include "mern-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
