apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  MONGO_USERNAME: {{ .Values.mongo.auth.appUsername | quote }}
  MONGO_PASSWORD: {{ .Values.mongo.auth.appPassword | quote }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.auth.rootUsername | quote }}
  
  # Look closely at how we stitch multiple variables together into one connection string!
  MONGODB_URI: "mongodb://{{ .Values.mongo.auth.rootUsername }}:{{ .Values.mongo.auth.appPassword }}@mongo-service:27017/{{ .Values.mongo.auth.database }}?authSource=admin"
