name: Deploy MERN App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build Backend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-backend:${{ github.sha }} ./backend

    - name: Build Frontend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-frontend:${{ github.sha }} ./frontend

    - name: Push images to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mern-backend:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/mern-frontend:${{ github.sha }}

    - name: Update Helm Values.yaml
      run: | 
        git config --global user.email "actions@github.com"
        git config --global user.name "github-actions"
        
        # Using sed to update specific image tags
        sed -i '/frontend:/,/tag:/ s/tag:.*/tag: "${{ github.sha }}"/' helm/mern-app/values.yaml
        sed -i '/backend:/,/tag:/ s/tag:.*/tag: "${{ github.sha }}"/' helm/mern-app/values.yaml
        
        git add helm/mern-app/values.yaml
        git commit -m "ci: update image tags to ${{ github.sha }}"
        git push